### ISSUE TITLE
[FABRIC] LunarClient Compatibilty

### ISSUE THREAD

**Issue by Omnikeck** [Adrenix/Nostalgic-Tweaks#58]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Fabric Loader Version: N/A
Fabric API Version: N/A
Nostalgic Tweaks Version: 1.20.1-Fabric-2.0.0-Beta

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Game Crashing during launch

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

[2024-02-14 13:38:09.037] [info]  java.lang.ClassCastException: class net.minecraft.client.gui.screens.AccessibilityOnboardingScreen cannot be cast to class com.moonsworth.lunar.RCICCIHHORIHRRIOICRCOIHRR.ORCOOCHOHOIOCCCHROHROCRHI.IOHHIIRCOCOHOHRIRHCORIOCI.ICOCOHCCRCHCHCRHROIOHORCO (net.minecraft.client.gui.screens.AccessibilityOnboardingScreen and com.moonsworth.lunar.RCICCIHHORIHRRIOICRCOIHRR.ORCOOCHOHOIOCCCHROHROCRHI.IOHHIIRCOCOHOHRIRHCORIOCI.ICOCOHCCRCHCHCRHROIOHORCO are in unnamed module of loader 'Genesis' @31428f76)
[2024-02-14 13:38:09.038] [info]  	at Genesis//net.minecraft.client.Minecraft.handler$zzg000$impl$setScreen(SourceFile:3265)
[2024-02-14 13:38:09.038] [info]  	at Genesis//net.minecraft.client.Minecraft.setScreen(SourceFile)
[2024-02-14 13:38:09.038] [info]  	at Genesis//net.minecraft.client.Minecraft.setInitialScreen(SourceFile:688)
[2024-02-14 13:38:09.038] [info]  	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:674)
[2024-02-14 13:38:09.039] [info]  	at Genesis//net.minecraft.client.main.Main.redirect$zbd000$impl$main$minecraft(SourceFile:639)
[2024-02-14 13:38:09.039] [info]  	at Genesis//net.minecraft.client.main.Main.main(SourceFile:211)
[2024-02-14 13:38:09.039] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-02-14 13:38:09.039] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2024-02-14 13:38:09.040] [info]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2024-02-14 13:38:09.040] [info]  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2024-02-14 13:38:09.040] [info]  	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[2024-02-14 13:38:09.041] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-02-14 13:38:09.041] [info]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2024-02-14 13:38:09.041] [info]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2024-02-14 13:38:09.041] [info]  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2024-02-14 13:38:09.042] [info]  	at com.moonsworth.lunar.genesis.IOHHIIRCOCOHOHRIRHCORIOCI.RCICCIHHORIHRRIOICRCOIHRR(Unknown Source)
[2024-02-14 13:38:09.042] [info]  	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
[2024-02-14 13:38:09.042] [info]  	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

N/A

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by forkiesassds** [comment]
Lunar Client is not supported as they obfuscate all their code, meaning to support Lunar it would require tons of hours reverse engineering everything and with every update the obfuscated names change meaning it's a waste of time to even support Lunar.

**Comment by Adrenix** [comment]
Yes, as mentioned above, Lunar is not supported. The obfuscated code makes this very difficult to find the issue.
